void cutscene() {
        int b;
                for(int a = 4; a >= 1; a--) {
                        clear();
                        attron(COLOR_PAIR(16 - ((a - 1) * 4)));
        printw("Once a day...");
                attroff(COLOR_PAIR(16 - ((a - 1) * 4)));
                refresh();
                if(a == 1) {
                        napms(3000);
                } else {
                napms(500);
                }
                }
                for(int a = 1; a <= 4; a++) {
                        clear();
                        attron(COLOR_PAIR(16 - ((a - 1) * 4)));
        printw("Once a day...");
                attroff(COLOR_PAIR(16 - ((a - 1) * 4)));
                refresh();
                if(a == 1) {
                        napms(3000);
                } else {
                napms(500);
                }
                }
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(5000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("##########v##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("##########@##########\n");
                printw("#         v         #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#         @         #\n");
                printw("#         v         #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#         @         #\n");
                printw("#         v         #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @         #\n");
                printw("#         v       # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("# What's that, prof?#\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("# A machine to...   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#   To what, prof?  #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("# A machine to...   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #<&           #\n");
                printw("#     #           # #\n");
                printw("#to explore 1D world#\n");
                printw("#####################\n");
                refresh();
                napms(4000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("# 1D world? Really? #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     # <&        # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #  <&       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#        ?!?        #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("# I need guinea pig #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#        So?        #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(4000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#        So?        #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #   &>      # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #    &>     # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #     &>    # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #      &>   # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #       &>  # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #       ^     #\n");
                printw("#     #       &   # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #       ^   # #\n");
                printw("#     #       &     #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v   ^     #\n");
                printw("#     #       &   # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @   ^   # #\n");
                printw("#         v   &     #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#             ^     #\n");
                printw("#         @   &   # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(50);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @  <&   # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#         @ <&    # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#         @<&     # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#         @<&       #\n");
                printw("#     #   v       # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #  <@<&     # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     # <@<&      # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #<@<&       # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#        NO!!!      #\n");
                printw("#     #@<&        # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#        NO!!!      #\n");
                printw("#     #<&         # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #<&         # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #<&           #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                b = getch();
                if(b == 'c') return;
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);


}
void cutscene2(int id, int index) {
        clear();
        std::string view = "";
                for(int j = (index < 3 ? 0 : index - 3); j <= ([&]() -> int {
                                if(index >= cond.size() - 1 - 5) {
                                return cond.size() - 1;
                                } else {
                                return index + 5;
                                }
                                })(); j++) {
                        view += std::string(cond[j] == 'c' ? "[@]" : (cond[j] != '0' ? "[X]" : "[ ]")) + " ";
                }
                view.pop_back();

                napms(2000);
                printw("Me: Where Am I?\n");
                refresh();
                napms(3000);
                printw("Professor: In 1D World\n");
                refresh();
                napms(4000);
                clear();
                printw("Me: Why you threw me here?\n");
                refresh();
                napms(5000);
                printw("Professor: Like I said, I need guinea pig. It's you\n");
                refresh();
                napms(7000);
                clear();
                printw("Me: Why you don't tell me before throw me?\n");
                refresh();
                napms(5000);
                printw("Professor: I too excited, It's first my discovery\n");
                refresh();
                napms(7000);
                clear();
                printw("Me: Why you always say \"first discovery\" every your discovery? Prof, this is the 286th your discovery, not first\n");
                refresh();
                napms(8000);
                printw("Professor: I don't know.\n");
                refresh();
                napms(3000);
                clear();
                printw("Me: You even don't tell me how to survival in this world\n");
                refresh();
                napms(5000);
                printw("Professor: Okay, first, you need to know, your body is actually near me, only your consciousness is put there.\n");
                refresh();
                napms(7000);
                clear();
                printw("Me: If this is not my body, when I killed here, I still alive?\n");
                refresh();
                napms(7000);
                printw("Professor: No, you still die. This is your consciousness, without that, you can't alive. Just fight them, don't be next to that.\n");
                refresh();
                napms(7000);
                clear();
                printw("%s\n", view.c_str());
                napms(1000);
                printw("Me: I see something, what's that?\n");
                refresh();
                napms(5000);
                printw("Professsor: That is your environment.\n");
                refresh();
                napms(5000);
                clear();
                printw("%s\n", view.c_str());
                printw("Me: I don't understand.\n");
                refresh();
                napms(3000);
                printw("Professor: Simply put, it's a map to show you the situation around you.\n");
                refresh();
                napms(8000);
                clear();
                addch('#'| COLOR_PAIR(id));
                printw("\n\n");
                printw("%s\n", view.c_str());
                refresh();
                napms(3000);
                printw("Me: I see something else, what's this?\n");
                refresh();
                napms(5000);
                printw("Professor: It's your right indication. Green mean safe, red mean danger, white mean you can pick it.\n");
                refresh();
                napms(7000);
                clear();
                addch('#'| COLOR_PAIR(id));
                printw("\n\n");
                printw("%s\n", view.c_str());
                printw("Me: I don't understand\n");
                refresh();
                napms(3000);
                printw("Professor: You'll understand. Your task is collect 200 block\n");
                refresh();
                napms(8000);
                clear();
                printw("Why I have a crazy professor.\n");
                refresh();
                napms(5000);
                clear();
}

void goodEnding() {
	int b;
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #>          # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #@>         # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     # @>        # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #  @>       # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #    @>     # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(200);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #     @>    # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(400);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#  Welcome back     #\n");
        printw("#####################\n");
        refresh();
        napms(3000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(3000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(3000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(1000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("# Why you threw me? #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(400);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("# Why you threw me? #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("# 'cuz I too excited#\n");
        printw("#####################\n");
        refresh();
        napms(800);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("# 'cuz I too excited#\n");
        printw("#####################\n");
        refresh();
        napms(1200);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#         Ah. yeah. #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
                for(int a = 1; a <= 4; a++) {
                        clear();
                        attron(COLOR_PAIR(16 - ((a - 1) * 4)));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#         Ah. yeah. #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
                attroff(COLOR_PAIR(16 - ((a - 1) * 4)));
                refresh();
                if(a == 1) {
                        napms(3000);
                } else {
                napms(500);
                }
                }
		clear();
		refresh();
		napms(3000);
		printw("Why I have a crazy professor. Again");
		refresh();
		napms(5000);
		clear();
		printw("Good ending.");
		refresh();
		napms(5000);
}

void badEnding() {
	int b;
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("# I pass my mission #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	for(int i = 0; i < 4; ++i) {
	clear();
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#   HAHAHAHHAHA     #\n");
        printw("#####################\n");
        refresh();
        napms(500);
	clear();
	attron(COLOR_PAIR(17));
        b = getch();
        if(b == 'c') return;
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#   HAHAHAHHAHA     #\n");
        printw("#####################\n");
        refresh();
        napms(500);
	attroff(COLOR_PAIR(17));
	}
	for(int i = 0; i < 4; ++i) {
	clear();
        b = getch();
        if(b == 'c') return;
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#######<&############\n");
        printw("####HAHAHAHHAHA######\n");
        printw("#####################\n");
        refresh();
        napms(500);
	clear();
	attron(COLOR_PAIR(17));
        b = getch();
        if(b == 'c') return;
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#######<&############\n");
        printw("####HAHAHAHHAHA######\n");
        printw("#####################\n");
        refresh();
        napms(500);
	attroff(COLOR_PAIR(17));
	}
	clear();
	refresh();
	napms(4500);
	printw("I.threw.was'nt.because.excitedness.");
	refresh();
	napms(5000);
	clear();
	printw("Bad ending.");
	refresh();
	napms(5000);
	clear();
	printw("SCP-256");
	refresh();
	napms(5000);

}

